services:

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - web-api-video
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: masstransit/rabbitmq:latest
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - web-api-video
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd  # Altere para uma senha forte
    ports:
      - 1433:1433
    networks:
      - web-api-video
    volumes:
      - sqlserver_data:/var/opt/mssql


  redis:
    image: redis:latest
    restart: always
    depends_on:
      - sqlserver
    ports:
      - 6379:6379
    networks:
      - web-api-video
    volumes:
      - redis_data:/data


  api-video:
    build:
      context: ./hackton-api
      dockerfile: Hackton.Api/Dockerfile
      args:
       version: 1
    depends_on:
      - redis
      - rabbitmq
      - sqlserver
    image: api-video
    ports:
      - 5144:8080
    networks:
      - web-api-video


  video-consumer:
    build:
      context: ./hackton-consumer
      dockerfile: Hackton.Consumer/Dockerfile
      args:
        version: 1
    depends_on:
      - rabbitmq
    image: video-consumer
    ports:
      - 6060:6060
    networks:
      - web-api-video

  prometheus:
    build:
      context: .
      dockerfile: prometheus/Dockerfile
      args:
        version: 1
    depends_on:
      - api-video
    image: prometheus-local
    restart: always
    ports:
      - 9090:9090
    networks:
      - web-api-video
    volumes:
      - prometheus_data:/prometheus/data:/data

  grafana:
    build:
      context: .
      dockerfile: grafana/Dockerfile
      args:
        version: 1
    depends_on:
      - prometheus
    image: grafana-local
    restart: always
    ports:
      - 3000:3000
    networks:
      - web-api-video
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  web-api-video:
    driver: bridge

volumes:
  redis_data:
  grafana_data:
  prometheus_data:
  sqlserver_data:
  rabbitmq_data:
  mongodb_data: