services:

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - web-api-video
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: masstransit/rabbitmq:latest
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - web-api-video
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - 1433:1433
    networks:
      - web-api-video
    volumes:
      - sqlserver_data:/var/opt/mssql

  api-video:
    build:
      context: ./hackton-api
      dockerfile: Hackton.Api/Dockerfile
      args:
       version: 1
    depends_on:
      - mongodb
      - rabbitmq
      - sqlserver
    image: api-video
    ports:
      - 5144:8080
    networks:
      - web-api-video


  video-consumer:
    build:
      context: ./hackton-consumer
      dockerfile: Hackton.Consumer/Dockerfile
      args:
        version: 1
    depends_on:
      - rabbitmq
      - api-video
      - mongodb
    image: video-consumer
    ports:
      - 6060:6060
    networks:
      - web-api-video


networks:
  web-api-video:
    driver: bridge

volumes:
  sqlserver_data:
  rabbitmq_data:
  mongodb_data: